"""new fields in user model

Revision ID: 28372c84bec1
Revises: e01061dd045f
Create Date: 2020-12-20 12:24:13.765121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "28372c84bec1"
down_revision = "e01061dd045f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("about_me", sa.String(length=140), nullable=True))
    op.add_column("user", sa.Column("last_seen", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "last_seen")
    op.drop_column("user", "about_me")
    # ### end Alembic commands ###
